modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="questing"
version="${file.jarVersion}"
displayName="Questing"
updateJSONURL="https://raw.githubusercontent.com/Toma1O6/UpdateSchemas/master/questing-forge.json"
displayURL="https://github.com/Toma1O6/Questing" # TODO change later
authors="Toma"
description='''
'''

[[dependencies.questing]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.questing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
